# Generated by Django 3.2.2 on 2021-06-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos_app', '0002_alter_cursos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
