# Generated by Django 3.2.2 on 2021-06-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos_app', '0003_alter_cursos_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
